FROM node:16.13-alpine3.13
ARG NODE_PORT=3000
ARG CERT_PATH=/
ARG DB_URL=x
ARG DB=x
ARG MOSQUITTO_BROKER_URL=x
ARG EMAILID=x
ARG PASSWORD=x
ENV NODE_PORT=${NODE_PORT}
ENV CERT_PATH=${CERT_PATH}
ENV DB_URL=${DB_URL}
ENV DB=${DB}
ENV MOSQUITTO_BROKER_URL=${MOSQUITTO_BROKER_URL}
ENV EMAILID=${EMAILID}
ENV PASSWORD=${PASSWORD}
WORKDIR /app
COPY ["package.json", "package-lock.json", "./"]
RUN mkdir certs
RUN npm install
COPY . .
EXPOSE ${NODE_PORT}
CMD ["npm", "start"]